services:
  - type: web
    name: finance-backend
    env: docker
    plan: free
    repo: https://github.com/your-username/your-repo-name
    dockerContext: ./Backend/finance-tracker-backend
    dockerfilePath: Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://finance-db:5432/financedb
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        value: your_password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
    dependsOn:
      - finance-db

  - type: web
    name: finance-frontend
    env: docker
    plan: free
    repo: https://github.com/your-username/your-repo-name
    dockerContext: ./Frontend/finance-tracker-ui
    dockerfilePath: Dockerfile
    dependsOn:
      - finance-backend

  - type: pserv
    name: finance-db
    env: docker
    plan: free
    dockerImage: postgres:15
    envVars:
      - key: POSTGRES_DB
        value: financedb
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: your_password
    persistentDisk:
      name: finance-db-disk
      mountPath: /var/lib/postgresql/data
      sizeGB: 1
